### ISSUE TITLE
Example parse-modify-write.js not working

### ISSUE THREAD

**Issue by sebastianandress** [exini/dicom-streams-js#31]
I'm trying to get the example working, however it throws the error `TypeError: dicom_streams_js_1.parseFlow is not a function`.
Please see the [sandbox link](https://codesandbox.io/s/nervous-darkness-q5osbb?file=/src/index.ts) to reproduce. How can I get the example working?

```
const got = require("got");
const dicomUrl =
  "https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/bbmri-53323851.dcm";

const src = got.stream(dicomUrl);

pipe(
  src,
  parseFlow(),
  toIndeterminateLengthSequences(),
  toUtf8Flow(),
  allowFilter([
    TagTree.fromTag(Tag.SpecificCharacterSet),
    TagTree.fromTag(Tag.PatientName),
    TagTree.fromTag(Tag.PatientName),
    TagTree.fromTag(Tag.StudyDescription),
    TagTree.fromTag(Tag.SeriesDate),
    TagTree.fromAnyItem(Tag.MACParametersSequence)
  ]),
  denyFilter([
    TagTree.fromAnyItem(Tag.MACParametersSequence).thenTag(
      Tag.DataElementsSigned
    )
  ]),
  modifyFlow(
    [
      TagModification.equals(TagPath.fromTag(Tag.PatientName), () =>
        Buffer.from("Anon 001")
      )
    ],
    [
      new TagInsertion(TagPath.fromTag(Tag.PatientIdentityRemoved), () =>
        Buffer.from("YES")
      )
    ]
  ),
  toBytesFlow()
);
```

Thanks a lot

**Comment by karl-exini** [comment]
Looks like you are mixing import and require statements. Try this:
`const { Tag, TagTree, TagPath, parseFlow, allowFilter, denyFilter, toIndeterminateLengthSequences, toUtf8Flow, TagModification, TagInsertion, modifyFlow, pipe, toBytesFlow } = require("@exini/dicom-streams-js");` instead of the import statement.
