### ISSUE TITLE
Example needed: browser usage

### ISSUE THREAD

**Issue by deluksic** [exini/dicom-streams-js#33]
This library looks really cool, and is solving a super important problem in medical imaging software!
I am however having trouble using it in the browser. I would like to create a custom anonymisation stream and pipe it to the server using the new `fetch` streaming upload feature in Chrome `v105` (see https://developer.chrome.com/articles/fetch-streaming-requests).

I'm using `vite` as the bundler. Due to `multipipe` package, I get `Buffer is not defined` when I try to `import {} from "@exini/dicom-streams-js"`. There are mentions of `__webpack_require__` in the stack, which could mean that the library is assuming usage of `webpack`.

Is there a way to not depend on `multipipe` in the browser environment?

EDIT: could be that I misunderstood this line. Could it be that you meant using electron for the frontend?
```
It can be used both on the backend using Node, as well as on the frontend.
```

**Comment by deluksic** [comment]
For vite users, `vite-plugin-node-polyfills` fixes the issues regarding `Buffer` and the `stream` package missing. Then, a utility to convert `ReadableStream` (web stream) to `Readable` is needed.

Still haven't managed to read a file without errors, but making progress.

Latest error I got:
```
byte-parser.ts:17 Uncaught Error: Parsing failed: 626840 bytes remain after finished parsing
    at InValue.onTruncation (byte-parser.ts:17:15)
    at ByteParser.flush (byte-parser.ts:97:34)
    ...
```

**Comment by karl-exini** [comment]
Thanks for the tip and report. Happy to help if you are able to share details on your test code. The error message you are seeing means that the parser got off the rails, something that usually only happens for corrupt or non-DICOM files.

**Comment by deluksic** [comment]
I accidentally added `encoding: 'binary'` to `Readable` when converting from `ReadableStream` (web stream). Without it works perfectly fine.

Closing.

**Comment by craigberry1** [comment]
>  Then, a utility to convert `ReadableStream` (web stream) to `Readable` is needed.

I was able to use [readable-web-to-node-stream](https://github.com/Borewit/readable-web-to-node-stream) for this.

**Comment by deluksic** [comment]
Please test whether backpressure works correctly. I believe I implemented my own back then because it didn't.
